/**
 * AppBucket UI will use some of key property
 * to retreive class names.
 * Use one of this utility in combination
 * with classnames module
 */

/**
 * Use the Props has a boolean value to
 * appen the right class. If value
 * fallback to true, className will be appended
 * @param {*} value The Props Value
 * @param {String} className The Classname to return
 * @param {String} elseClassName Classname to use if value is falsy
 *
 * @example
 * <Button primary />
 * <button class="is-primary"></button>
 */
export const classByKey = (value, className, elseClassName) => (value ? className : elseClassName);

/**
 * Classname that will append 'is-' keyword
 * to property
 * @param {*} value The Props Value
 * @param {String} className The Classname to use
 *
 * @example
 * <Column is={8} />
 * <div class="column is-8"></div>
 */
export const isValue = value => (value && value !== true ? `is-${value.toString()}` : false);

/**
 * Classname that will replace a pattern
 * @param {String} value The Props Value
 * @param {String} classNamePattern The Classname pattern to use
 *
 * @example
 * classByPattern(width, 'is-%value%-width');
 *
 * <Layout width='phone' />
 * <div class="container is-phone-width"></div>
 */
export const classByPattern = (value, classNamePattern) => (typeof value === 'string' || typeof value === 'number') && classNamePattern.replace('%value%', value.toString().replace(/\s/g, '-'));

/**
 * Classname that will be generated by value
 * @param {String} value The Props Value
 *
 * @example
 * classByValue(verticalAlign)
 *
 * <Layout.Row verticalAlign='on top' />
 * <div class="with-columns on-top"></div>
 */
export const classByValue = value => typeof value === 'string' && value.toLowerCase().replace(/\s/g, '-');

/**
 * Classname generated using responsive property
 * @param {Boolean|String} value The Props Value
 * @param {String} baseClass The base classname to use
 *
 * @example
 * responsiveClass(withoutGap, 'without-gap')
 *
 * <Layout.Row withoutGap />
 * <div class="with-columns without-gap" />
 *
 * @example
 * <Layout.Row withoutGap='on tablet' />
 * <div class="with-columns on-tablet-without-gap" />
 */
export const responsiveClass = (value, baseClass) => (
  value === true
    ? baseClass
    : typeof value === 'string'
      ? `${value.toLowerCase().replace(/\s/g, '-')}-${baseClass}`
      : false
);
